theme: jekyll-theme-minimal
title: [Explicit Versioning]
description: [A versioning system for Content Management Systems | WordPress | Joomla | Drupal      <a href="http://molpopgen.github.io/fwdpp">Home</a>
        <br>
        <a href="http://molpopgen.github.io/fwdpp/doc/md/overview.html">Library overview</a>
        <br>
        <a href="http://molpopgen.github.io/fwdpp/doc/html/index.html">Reference manual</a>
        <br>
        <a href="https://groups.google.com/forum/#!forum/fwdpp-users">Google Group</a>
        <br>
        <a href="http://molpopgen.github.io/fwdpp/doc/md/examples.html">Example programs</a>
        <br>
]